### ISSUE TITLE
Mean direction parameter problem

### ISSUE THREAD

**Issue by JiReilly** [gvoulgaris0/WavePart#10]
Hi!
First, thanks for sharing this code.
I'm using it with some SWAN files (so I had to modify the input section for variables, as I have nautical coord and a logarithmic frequency delta). Actually, I'm able to run the code and do partitioning, but  it seems there is a problem related with parameters we can extract from spectra. 
The mean direction (for total spectrum and partitions) is a value very close to zero in every timeline I plot, even if the 3D plots and polar plots show a different situation.
So I tried to plot the mean dir with the sample file provided and I had the same situation.
Could you check if this is a general case for every input file?
Thanks in advance.
![meand dir sample file](https://user-images.githubusercontent.com/57893397/75772078-8bf15200-5d4b-11ea-8532-4b89e2cd87e5.png)

**Comment by gvoulgaris0** [comment]
Hi JiReilly, and apologies for the super-delayed response. I checked the code with the example and using the example file (first 16 spectra) but I cannot replicate your issues. I get non-zero directions. 

![meandir](https://user-images.githubusercontent.com/48567321/126872176-ded3d130-e1c5-4f33-8ec5-9ac7a26e4a35.jpg)

Look as the function
